//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CataExchange2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billetera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billetera()
        {
            this.Comercia = new HashSet<Comercia>();
            this.OperaCripto = new HashSet<OperaCripto>();
        }
    
        public int idBilletera { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string clavePublica { get; set; }
        public string nombreCripto { get; set; }
        public Nullable<double> cantidadCripto { get; set; }
        public Nullable<double> cotizacion { get; set; }
        public string imagen { get; set; }
        public string simbolo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comercia> Comercia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperaCripto> OperaCripto { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
