//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CataExchange2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enviaDeposita
    {
        public int idEnviaDeposita { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCuentaPesos { get; set; }
        public decimal monto { get; set; }
        public string tipoOperacion { get; set; }
    
        public virtual cuentaPesos cuentaPesos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
